from .Class import Class as Class
from .School import School as School
from .Fib import Fib as Fib
from .MatchA import MatchA as MatchA
from .MatchB import MatchB as MatchB
from .Mcq import Mcq as Mcq
from .QuestionDetails import QuestionDetails as QuestionDetails
from .QuestionDifficulty import QuestionDifficulty as QuestionDifficulty
from .QuestionImages import QuestionImages as QuestionImages
from .QuestionSubquestionMap import QuestionSubquestionMap as QuestionSubquestionMap
from .QuestionType import QuestionType as QuestionType
from .ReasonAssertion import ReasonAssertion as ReasonAssertion
from .School import School as School
from .Subject import Subject as Subject
from .Test import Test as Test
from .TestQuestionMap import TestQuestionMap as TestQuestionMap
from .TestSectionMap import TestSectionMap as TestSectionMap
from .TestType import TestType as TestType
from .Mcq import toMcq as toMcq
